version: '3'
services:

  api-mkapi:
    depends_on:
      - postgres-mkapi
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_SERVER: postgres-mkapi
      DB_NAME: postgres
      DB_TYPE: postgres
      SMTP_HOST: goldkeytechnologies.com
      SMTP_PORT: 465
      SMTP_USER: no-reply@collabizus.com
      SMTP_PASSWORD: Scorpio(@)22
      
  postgres-mkapi:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
